name: basic_utils
description: Common util classes for Strings, Dates, X509, PKCS, Cryptographie and more.
version: 5.7.1
homepage: https://www.cyberneid.com
publish_to: https://pubdev.cyberneid.com/
authors:
  - cyberneid
  - ugo chirico
  - Francesco Orlando

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  http: ^1.1.0
  logging: ^1.2.0
  json_annotation: ^4.8.1
  pointycastle: ^3.7.3

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.8

false_secrets:
 - /test/crypto_utils_test.dart
 - /test/pkcs12_utils_test.dart
